// <auto-generated />
using System;
using Dragon.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dragon.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dragon.Model.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Category");

                    b.Property<string>("Description");

                    b.Property<byte[]>("Poster");

                    b.Property<Guid?>("ScheduleTimeId");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleTimeId");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("Dragon.Model.Schedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("ScheduleTime");

                    b.HasKey("Id");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("Dragon.Model.Movie", b =>
                {
                    b.HasOne("Dragon.Model.Schedule", "ScheduleTime")
                        .WithMany()
                        .HasForeignKey("ScheduleTimeId");
                });
#pragma warning restore 612, 618
        }
    }
}
